name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.12

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Coverage
      run: |
        COVERAGE="$(go test -covermode=count -coverprofile=cover.out ./... \
          | grep -Po '(?<=coverage: )[0-9.]+(?=% of statements)')"
        REF=${{ github.ref }}
        IFS='/' read -ra PATHS <<< "$REF"
        BRANCH="${PATHS[1]}_${PATHS[2]}"

        echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV

        echo "coverage: $COVERAGE";
        echo "github.ref: $REF"
        echo "branch: $BRANCH"

        go tool cover -html=cover.out -o cover.html

        curl \
          -X PATCH \
          -H "Authorization: bearer ${{ secrets.GIST_SECRET }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -d "{\"files\":{\"starlet__$BRANCH.html\":{\"content\":$(jq -Rs . < cover.html)}}}" \
          https://api.github.com/gists/dab69a116cf1a97577a1194a1e67ab55

    - name: Create coverage badge
      uses: schneegans/dynamic-badges-action@v1.3.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: dab69a116cf1a97577a1194a1e67ab55
        filename: starlet__${{ env.BRANCH }}.json
        label: Test Coverage
        message: ${{ env.COVERAGE }}%
        minColorRange: 0
        maxColorRange: 100
        valColorRange: ${{ env.COVERAGE }}
        namedLogo: Go
